### ISSUE TITLE
geojson

### ISSUE THREAD

**Issue by abillits** [weacast/weacast-gtiff2json#10]
Would there be a way to modify this to output geojson?

**Comment by claustres** [comment]
Hi, what is exactly the use case for this kind of output ? Indeed geotiff is used for raster (ie gridded) data so that the output of each pixel as a polygon will be larger that the pixel values themselves. It is usually simpler to recreate the underlying geometry from the grid/projection information if required.

**Comment by abillits** [comment]
I've found another solution but my reasoning for this was that geojson is more compatible with tile servers.
